### ISSUE TITLE
'You must use a valid publishable key to create a token. For more info, see https://stripe.com/docs/stripe.js'

### ISSUE THREAD

**Issue by tharrington** [lrettig/react-native-stripe-new#10]
I am getting this error, but I have clearly copied and pasted my pub key from my Stripe account. Any ideas?

Also, so long as I have a token, can I charge the card or does the user have to authorize?

**Comment by lrettig** [comment]
Hi @tharrington, sorry for the slow response. Can you confirm that you're calling `StripeNative.init` with your Stripe publishable key before calling any of the other methods? That error appears to be coming from the [Stripe native code](https://github.com/stripe/stripe-ios/blob/master/Stripe/STPAPIClient.m#L137) when the key hasn't been set.

Yes, as soon as you have a token, you can create a charge in Stripe, using either their API or web dashboard. The user does not need to authorize future charges.

**Comment by lrettig** [comment]
Closing, let me know if the issue persists
