### ISSUE TITLE
Getting Property not found error

### ISSUE THREAD

**Issue by KartikTalwar** [lrettig/react-native-stripe-new#12]
Hello,

I just tried to get this setup and after installing the libraries and clicking build, my build fails with the following error

```
/Users/kartik/github/test-app/node_modules/react-native-stripe/StripeNative/PaymentViewController.m:125:76: Property 'cardParams' not found on object of type 'STPPaymentCardTextField *'
```

Do you know what is happening here?

Thanks

**Comment by lrettig** [comment]
Hi @KartikTalwar, sorry but I haven't seen or heard of this issue before. `cardParams` and `STPPaymentCardTextField` are coming from Stripe, per https://stripe.com/docs/mobile/ios.

**Comment by KartikTalwar** [comment]
I ended up figuring it out, forgot to give an update here. 
There is a typo: 

https://github.com/lrettig/react-native-stripe/blob/master/StripeNative/PaymentViewController.m#L125

this arg should be `self.paymentTextField.card`

**Comment by lrettig** [comment]
Thanks for letting us know
