### ISSUE TITLE
Install breaks my build

### ISSUE THREAD

**Issue by mlevkovsky** [lrettig/react-native-stripe-new#17]
So everything installs fine and I have cocoapods but when I install everything this is the error I get in the console

no such file or directory, open '.../node_modules/react-native-stripe-api/node_modules/react-native/Libraries/Network/XMLHttpRequest.ios.js'

Not sure how to would proceed. Thanks

**Comment by mlevkovsky** [comment]
My bad, that was quite a brain fart. Forgot to close my console before rebuilding. I re-build after that and everything is fine.
Sorry about that

**Comment by lrettig** [comment]
Awesome thanks for letting me know you worked it out!
