### ISSUE TITLE
Cannot run sample app

### ISSUE THREAD

**Issue by AndreyNikiforov** [lrettig/react-native-stripe-new#18]
I am following steps in the repo and getting build error: 

/Users/andrey/Projects/react-native-stripe/StripeNative/PaymentViewController.m:11:9: fatal error: 'Stripe/Stripe.h' file not found
# import <Stripe/Stripe.h>

```
    ^
```

1 error generated.

Please advise.

**Comment by lrettig** [comment]
Hi @AndreyNikiforov so sorry for the slow response. Can you please confirm whether you've followed all of the steps at https://github.com/lrettig/react-native-stripe#installation exactly? Thanks

Let me know if you already worked this out

**Comment by lrettig** [comment]
Let me know if still an issue
