### ISSUE TITLE
Touch Id Authentication

### ISSUE THREAD

**Issue by dmbrowne** [lrettig/react-native-stripe-new#20]
HI, I don't know if i'm using the library correctly, but is it possible to use touch id instead of passcode for authenticating the apple pay?

**Comment by richardgill** [comment]
For me it does it by default. The simulator has a button you press which on a real device for me uses the touch id.

**Comment by dmbrowne** [comment]
how/where is that button?
does it need it be enabled?

**Comment by richardgill** [comment]
So for me this pops up:

<img width="316" alt="screen shot 2016-09-09 at 17 11 06" src="https://cloud.githubusercontent.com/assets/6640874/18394179/84b5b704-76b0-11e6-8991-96f957cd0c78.png">

**Comment by dmbrowne** [comment]
yes, same for me. A little background; I'm not an iPhone user so please excuse any questions that may come across as stupid. But would the user have the option to use touch id or passcode based on their preferences/settings?

**Comment by richardgill** [comment]
So, where it says 'Pay with Passcode' that will be a touch id on iphone 6/6+ and greater. 

On phones without apple pay, i've detected that and done something else manually (a hand rolled payments form).

As far as I know there isn't an option to passcode based on preferences.

**Comment by lrettig** [comment]
Agree, I think apple pay only works with the touch ID

**Comment by dmbrowne** [comment]
ok guys, thanks for the clarification. I believe I can close this issue now 👍
