### ISSUE TITLE
Apple Pay Configuration Error

### ISSUE THREAD

**Issue by haihoang20** [lrettig/react-native-stripe-new#26]
I've set up everything and have enabled Apple Pay in Xcode. Detecting Apple Pay in the simulator as well as on a physical device are working, however when I try to call 

`StripeNative.paymentRequestWithApplePay`

It throws an error: "Apple Pay Configuration Error" so I can't get the token. Do you have any tips for where I might be going wrong?

Thanks!

**Comment by haihoang20** [comment]
All good. I realized that I was calling init() incorrectly since I was following the example provided in the docs. I was missing the second parameter (merchant ID).

**Comment by lrettig** [comment]
Thanks for letting us know what happened here!
