### ISSUE TITLE
Wont build anymore

### ISSUE THREAD

**Issue by imclean** [lrettig/react-native-stripe-new#27]
I'm getting this error on build
`npm ERR! Darwin 15.6.0
922
    npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "--no-color" "install" "--loglevel" "info"
923
    npm ERR! node v5.6.0
924
    npm ERR! npm  v3.6.0
925
    npm ERR! code ELIFECYCLE
926
    npm ERR! react-native-stripe@1.2.1 postinstall: `bash postinstall.sh`
927
    npm ERR! Exit status 1
928
    npm ERR! 
929
    npm ERR! Failed at the react-native-stripe@1.2.1 postinstall script 'bash postinstall.sh'.
930
    npm ERR! Make sure you have the latest version of node.js and npm installed.
931
    npm ERR! If you do, this is most likely a problem with the react-native-stripe package,
932
    npm ERR! not with npm itself.
933
    npm ERR! Tell the author that this fails on your system:
934
    npm ERR!     bash postinstall.sh
935
    npm ERR! You can get information on how to open an issue for this project with:
936
    npm ERR!     npm bugs react-native-stripe
937
    npm ERR! Or if that isn't available, you can get their info via:
938
    npm ERR!     npm owner ls react-native-stripe
939
    npm ERR! There is likely additional logging output above.
940
    npm ERR! Please include the following file with any support request:
941
    npm ERR!     /private/tmp/sandbox/workspace/npm-debug.log`

**Comment by raspasov** [comment]
Getting the same thing - any thoughts?

**Comment by imclean** [comment]
You have to ask Buddybuild to add a pre build script so it doesn't call the pod installation, that is what is in the post install script

**Comment by lrettig** [comment]
Do you have cocoapods installed? Please reopen if still an issue
