### ISSUE TITLE
can you update the version

### ISSUE THREAD

**Issue by jjhesk** [lrettig/react-native-stripe-new#29]
is this possible to update the support react native version to 0.42.0

**Comment by lrettig** [comment]
Did you try this with RN 0.42.0? Was there an issue? I haven't tested with the more recent versions

**Comment by stokesbga** [comment]
There is a build fail issue with StripeNative>StripeNativeManger.m. Just needs to update

``` #import "RCTEventDispatcher.h"``` 

with

``` #import <React/RCTEventDispatcher.h>```

**Comment by lrettig** [comment]
Fixed in #32, thanks
