### ISSUE TITLE
Pod install not working

### ISSUE THREAD

**Issue by jackread** [lrettig/react-native-stripe-new#33]
<pre><code>Unable to find host target(s) for StripeNative. Please add the host targets for the embedded targets to the Podfile.</code></pre>

I get this installing from npm

**Comment by lrettig** [comment]
Removed cocoapods in https://github.com/lrettig/react-native-stripe/commit/e133a30226cab80a748669ce0483b1c569a282f0, this is no longer an issue. Thanks.
