### ISSUE TITLE
Stripe/Stripe.h

### ISSUE THREAD

**Issue by sarlv** [lrettig/react-native-stripe-new#34]
When I try to run project in Xcode I get this error: 'Stripe/Stripe.h' file not found
Can you say what is the reason?

Thanks

**Comment by stokesbga** [comment]
Did you install stripe? It's kind of implied here but not totally obvious haha

**Comment by sarlv** [comment]
Unfortunately I did not add SDK properly. Thanks for your feedback! The problem was solved.

**Comment by lrettig** [comment]
Thanks @stokesbga, closing

**Comment by AvishyBD** [comment]
Hi @sarlv,
I keep running into the same error - can you tell me exactly how you fixed it?
Thanks,
Avishy.

**Comment by sarlv** [comment]
@AvishyBD Hi! Try to change your package version.

**Comment by AvishyBD** [comment]
Hi @sarlv - thanks for the reply!

I tried several version, still no joy...
Which versions of the Stripe, and the StripeNative packages work for you?

(P.S. I'm using cocoapods for the Stripe SDK - how did you install it?)
