### ISSUE TITLE
Payment request is invalid: check your entitlements

### ISSUE THREAD

**Issue by dmcfaul** [lrettig/react-native-stripe-new#4]
I keep getting this result when trying to charge items on a device. I've followed the steps documented by stripe here: https://stripe.com/docs/mobile/apple-pay and I've made sure to turn on apple pay in the xcode capabilities section. I've tried with two separate merchant id's created specifically for this process and two different certs. I'm also setting the merchant id in the app as per your latest commit.

**Comment by lrettig** [comment]
Sorry to hear you've run into this problem, that sounds frustrating. Some basic troubleshooting steps:
- Does your app have an entitlements file (in Xcode), and does it contain your merchant ID? (I think Xcode set this up automatically for me)
- When you view your App ID on Apple's developer site, under Entitlements, is Apple Pay green?
- Under your app settings > General > Identity, is the right Team selected?
- Under Build Settings > Code Signing, is the right code signing identity and provisioning profile selected? In particular, this, and the Team, both need to match the apple developer ID account with the merchant ID.
- Have you created the Apple Pay certificate and uploaded it to Stripe?

I've never run into this error myself. Could you post a stack trace or any more info on where it's coming from?

**Comment by dmcfaul** [comment]
Hello, I have tried all of the steps that you mentioned with the same result. There is no stack trace, just the error message printed in the xcode debug panel. I'm assuming it's done in the stripe framework. Anyways, this doesn't appear to be your libraries' issue, so I'll close this out. If I find a solution I'll be sure to update here. Thanks for the response!

**Comment by lrettig** [comment]
Please keep us updated! Did you try posting to StackOverflow?

**Comment by dmcfaul** [comment]
@lrettig does your entitlements file contain an entry for apple pay after you turn it on in xcode's capabilities pane? if so, could you cut 'n paste that entry for me? (minus the secret bits of course..) It seems like turning on the apple pay capability doesn't update my entitlements file and I can't figure out what the correct entry is for me to manually add it.

**Comment by lrettig** [comment]
Yup! Here's the entitlements file in its entirety:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>com.apple.developer.in-app-payments</key>
    <array>
        <string>my-merchant-id</string>
    </array>
</dict>
</plist>
```

**Comment by dmcfaul** [comment]
I figured out the root cause of this issue..I was using v1.0.2 and my merchant id wasn't getting to Apple. Thanks for your help @lrettig !

**Comment by lrettig** [comment]
Glad to hear it worked out! Thanks for letting us know the problem.
