### ISSUE TITLE
npm install fails if cocoapods isn't installed

### ISSUE THREAD

**Issue by lrettig** [lrettig/react-native-stripe-new#5]
For anyone who randomly tries to install this module, but doesn't happen to already have cocoapods installed, they'll just see `npm install` fail with no explanation.

`postinstall.sh` should be updated to check for cocoapods and print a useful error message if it's missing.

**Comment by tiffanyricks** [comment]
Hi @lrettig  This file does not work because it does not reference a target.  Can I contribute to this project?   I have some changes in my local repo that has fixed these issues.  I have also created a podspec for this project to allow installs using cocoapods.

**Comment by lrettig** [comment]
Hi @tiffanyricks thanks for letting me know. This should be fixed in https://github.com/lrettig/react-native-stripe/pull/11. Please let me know if you're still seeing any problems, and feel free to contribute!

**Comment by lrettig** [comment]
Oops, the original issue here still exists

**Comment by lrettig** [comment]
Cocoapods removed in https://github.com/lrettig/react-native-stripe/commit/e133a30226cab80a748669ce0483b1c569a282f0, no longer an issue
