### ISSUE TITLE
"Too many arguments to block call" error when running example

### ISSUE THREAD

**Issue by AndreyNikiforov** [lrettig/react-native-stripe-new#7]
Got latest (69e39d3a9) and tried running example. Xcode gives error:

`/Users/andrey/Projects/react-native-stripe/StripeNative/StripeNativeManager.m:137:34: Too many arguments to block call, expected 1, have 3`

that is line with `promiseRejector(nil, nil, error);`

there 6 more errors with the same message.

Do you have any advice how to make example running?

**Comment by lrettig** [comment]
Hi Andrey, which version of react native are you using? It looks like it
might be outdated--I think this changed around 0.19. Thanks.

**Comment by AndreyNikiforov** [comment]
i was using RN 0.21. Looked as error was related to stripe code. I've moved on, so closing the issue.

**Comment by lrettig** [comment]
Thanks for letting us know
