### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by AndreyNikiforov** [lrettig/react-native-stripe-new#8]
Are there any plans to add Android support?

**Comment by lrettig** [comment]
Hi @AndreyNikiforov, I considered doing this for Android but the main value of this library is its support for Apple Pay. If you're collecting credit card details manually and just doing Stripe payments, you should be able to do that pretty easily using Stripe's REST API. (Note that, last time I checked, react native did not support the Stripe JS API.)

I'd welcome a PR but I don't have plans to add android support yet.

Thanks.
