### ISSUE TITLE
Change currency?

### ISSUE THREAD

**Issue by richardgill** [lrettig/react-native-stripe-new#9]
Is it possible to switch which currency the payment is made in? Right now it seems to default to $. 

Thanks,

Richard

**Comment by lrettig** [comment]
Hi @richardgill, thanks for the question. This isn't supported at the moment. Definitely welcome a PR as I'm not sure when I'll be able to get around to it. To point you or whoever works on this in the right direction, the change would probably have to be made to https://github.com/lrettig/react-native-stripe/blob/master/StripeNative/StripeNativeManager.m around line 91 where the [PKPaymentRequest](https://developer.apple.com/library/ios/documentation/PassKit/Reference/PKPaymentRequest_Ref/index.html) is constructed.

**Comment by richardgill** [comment]
How would you make the currency configurable? Through the options object?

**Comment by lrettig** [comment]
I think you'd have to set the `currencyCode` on the `paymentRequest` object (see [Apple Docs](https://developer.apple.com/library/ios/documentation/PassKit/Reference/PKPaymentRequest_Ref/index.html#//apple_ref/occ/instp/PKPaymentRequest/currencyCode))--you'd probably want to set this on the `options` object passed into `paymentRequestWithApplePay` in `index.ios.js` and pass that down into the native code.
